#! /usr/bin/Rscript

# plot_Hybrid_Web.R
#
# Adapted from C. Liu's plot_Hybrid script.
# create a png file depicting the hybridization
# described by its input arguments.  The file name
# is created using the site number given as an argument.
#
# Modifications are
#    added a parameter to plot_Hybrid for site id, needed to create file name
#    created a main program to capture command line arguments and launch plot hybrid
#    cleaned up the indenting so the code was easier for me to read.
#
# little error checking is done.  This script should
# be used with caution.  It assumes input is correct.
#
# usage plot_Hybrid_Web.R <Site ID> <Target Name> <miRNA Name> <site position> <Tar MisMat> <Tar Mat> <miRNA Mat> <miRNA MisMat> <dG Hybrid>
#

# GLOBALS

guPair <<- "|"; 
guCex <<- 0.6;
wcCex <<- 1;  
diaMRatio <<- 2/3; 
fontCex <<- 0.8;
widPair <<- 0.025 * fontCex; 
widLoop <<- 0.02 * fontCex;  
heiPair <<- 0.03 * fontCex;    
heiLoop <<- 0.025 * fontCex;

#guPair <<- "|"; 
#guCex <<- 0.6;
#wcCex <<- 2;  
#diaMRatio <<- 2/3; 
#fontCex <<- 1.6;
#widPair <<- 0.025 * fontCex; 
#widLoop <<- 0.02 * fontCex;  
#heiPair <<- 0.03 * fontCex;    
#heiLoop <<- 0.025 * fontCex;

# FUNCTIONS

# plot_Hybrid
#
# Author C. Liu
# Takes alignment information generated by RNAHybrid and creates
# a png file containing a labeled diagram.
#
# Parameters
#       site -- array containing information on binding site
#       startX -- optional
#       startY -- optional
# Return -- none
# Precondition
#       The following globals should be defined.
#       guPair, guCex, wcCex, diaMRatio, fontCex,
#       widPair, heiPair, heiiLoop
#
plot_Hybrid =function(site,startX=0.1,startY=0.5){
    # Example for input
    #                       Site ID	site[1]: integer  Unique site number, used for file name
    #			Target name	site[2]: H19 or NM_000014
    #			miRNA name	site[3]: let-7a
    #		        site position	site[4]: 100-130
    #                       Target    5'site[5]: A    UAUC   UUAUUUAC     UUGAA      G   3'  
    #                                   site[6]:  GAAG    UGC        AAUCU     GCAAAA      
    #                                   site[7]:  CUUU    ACG        UUGGA     CGUUUU      
    #                       miRNA  3'	site[8]: A           U                       GA  5'
    #		        DeltaG_hybrid	site[9]: -22

    tar_mis = unlist(strsplit(site[5],""));
    tar_match = unlist(strsplit(site[6],""));
    mir_match = unlist(strsplit(site[7],""));
    mir_mis = unlist(strsplit(site[8],""));
    sitePos = as.numeric(unlist(strsplit(site[4],"-")));

    png(file=paste("Site",site[1],".png",sep=""));
	
    #find out the start and end position for base-pairing, and length of helix and length of loop.
    Index = which(tar_match!=" ");
    ind = which(c(Index,0)-c(-1,Index)>1);
    bpStartPos = Index[ind]; nHelix = length(bpStartPos);
    bpEndPos = Index[c(ind[-1]-1,length(Index))]; rm(Index,ind);
    bpLeng = bpEndPos-bpStartPos+1;
    N = length(mir_mis);
    loopStartPos = bpEndPos[-nHelix]+1;
    loopEndPos = bpStartPos[-1]-1; #rm(bpStartPos,bpEndPos);

    posTrack_tar = matrix(0,2,length(which(tar_match!=" " | tar_mis!=" ")));target = character(ncol(posTrack_tar));count_tar = 1;
    posTrack_mir = matrix(0,2,length(which(mir_match!=" " | mir_mis!=" ")));miRNA = character(ncol(posTrack_mir));count_mir = 1;

    plot.new();
	
    #for left end	
    if (bpStartPos[1]>1) {
       for (j in 1:(bpStartPos[1]-1)) {
       	   if (mir_mis[j]!=" ") {
	      posTrack_mir[,count_mir]=c(startX+j*widLoop,startY+(bpStartPos[1]-j)*heiLoop);
	      miRNA[count_mir] = mir_mis[j]; count_mir = count_mir+1;
	   }
	   if (tar_mis[j]!=" ") {
	      posTrack_tar[,count_tar]=c(startX+j*widLoop,startY-2*heiPair-(bpStartPos[1]-j)*heiLoop);
	      target[count_tar] = tar_mis[j]; count_tar = count_tar+1;
	   } 
	} # end for  
    } # end if
    targetBPstart = count_tar;
    startX = startX+(bpStartPos[1])*widLoop;
	
    #for helix	and loop
    titleStartX = startX;
    titleTopY = startY+3*heiPair;
    titleBotY = startY-5*heiPair;

    for (i in 1:nHelix){   #for base pair symbol
    	tmpX = startX+(0:(bpLeng[i]-1))*widPair; tmpY = rep(startY-heiPair,bpLeng[i]);
	ind = which(is.element(paste(tar_match[bpStartPos[i]:bpEndPos[i]],mir_match[bpStartPos[i]:bpEndPos[i]],sep=""),c("GU","UG")));
	if (length(ind)>0) text(tmpX[ind],tmpY[ind],guPair,cex=guCex,font=2);
	if (length(ind)<bpLeng[i]) points(tmpX[setdiff(1:bpLeng[i],ind)],tmpY[setdiff(1:bpLeng[i],ind)],pch=20,cex=wcCex);
			
	posTrack_mir[,count_mir+0:(bpLeng[i]-1)]=rbind(startX+(0:(bpLeng[i]-1))*widPair,rep(startY,bpLeng[i]));
	miRNA[count_mir+0:(bpLeng[i]-1)] = mir_match[bpStartPos[i]:bpEndPos[i]]; count_mir = count_mir+bpLeng[i];
			
	posTrack_tar[,count_tar+0:(bpLeng[i]-1)]=rbind(startX+(0:(bpLeng[i]-1))*widPair,rep(startY-heiPair*2,bpLeng[i]));
	target[count_tar+0:(bpLeng[i]-1)] = tar_match[bpStartPos[i]:bpEndPos[i]]; count_tar = count_tar+bpLeng[i];
	startX = startX+(bpLeng[i]-1)*widPair;
		
	if (i<nHelix){	#for loop	
	   startX = startX+0.5*widLoop;
	   tmp = tar_mis[loopStartPos[i]:loopEndPos[i]]; tar_loop = tmp[tmp!=" "];
	   tmp = mir_mis[loopStartPos[i]:loopEndPos[i]]; mir_loop = tmp[tmp!=" "]; rm(tmp);
	   len_tar_loop = length(tar_loop); len_mir_loop = length(mir_loop);
	   if (len_tar_loop>=len_mir_loop) diaM = (len_tar_loop^(diaMRatio))*widPair else diaM = (len_mir_loop^(diaMRatio))*widPair;
				
	   if (len_mir_loop>0) {
	      mirY = startY+(1:ceiling(len_mir_loop/2))*heiPair; 
	      topRatio = 1/(len_mir_loop^(diaMRatio+0.1));
	      if (len_mir_loop%%2==0) topY = mirY[length(mirY)]+heiPair*topRatio else topY = mirY[length(mirY)];
	      #if (len_mir_loop == 2) topY = topY+heiPair*0.1;
	      mirX = sqrt((mirY-topY)*diaM^2/4/(startY-topY));	
	      if (len_mir_loop%%2==0) {
	      	 mirX = c(startX+diaM/2-mirX, startX+diaM/2+rev(mirX));
		 mirY = c(mirY, rev(mirY))
	      } 
	      else {
	      	 mirX = c(startX+diaM/2-mirX, startX+diaM/2+rev(mirX[-length(mirX)]));
		 mirY = c(mirY,rev(mirY[-length(mirY)]))
	      }
	      posTrack_mir[,count_mir+0:(len_mir_loop-1)]=rbind(mirX,mirY);
	      miRNA[count_mir+0:(len_mir_loop-1)] = mir_loop; count_mir = count_mir+len_mir_loop;
	      if (titleTopY < max(mirY)+2*heiPair) titleTopY = max(mirY)+2*heiPair;
	   }
	   if (len_tar_loop>0) {
	      tarY = startY-2*heiPair-(1:ceiling(len_tar_loop/2))*heiPair;
	      topRatio = 1/(len_tar_loop^(diaMRatio+0.1));
	      if (len_tar_loop%%2==0) topY = tarY[length(tarY)]-heiPair*topRatio else topY = tarY[length(tarY)];
	      tarX = sqrt((tarY-topY)*diaM^2/4/(startY-2*heiPair-topY));
	      if (len_tar_loop%%2==0) {
	      	 tarX = c(startX+diaM/2-tarX, startX+diaM/2+rev(tarX));
		 tarY = c(tarY, rev(tarY));
	      } 
	      else {
		 tarX = c(startX+diaM/2-tarX, startX+diaM/2+rev(tarX[-length(tarX)]));
		 tarY = c(tarY,rev(tarY[-length(tarY)]));
	      }
	      posTrack_tar[,count_tar+0:(len_tar_loop-1)]=rbind(tarX,tarY);
	      target[count_tar+0:(len_tar_loop-1)] = tar_loop; count_tar = count_tar+len_tar_loop;
	      if (titleBotY > min(tarY)-3*heiPair) titleBotY = min(tarY)-3*heiPair;
				}
	      startX = startX+diaM+0.5*widLoop;
	}
    }
 
   #for right end	
    titleEndX = startX;
    targetBPend = count_tar-1;
    
    if (bpEndPos[nHelix]<N) {
       for (j in (bpEndPos[nHelix]+1):N) {
       	   if (mir_mis[j]!=" ") {
	      posTrack_mir[,count_mir]=c(startX+(j-bpEndPos[nHelix])*widLoop,startY+(j-bpEndPos[nHelix])*heiLoop);
	      miRNA[count_mir] = mir_mis[j]; count_mir = count_mir+1;
	   }
	   if (tar_mis[j]!=" ") {
	      posTrack_tar[,count_tar]=c(startX+(j-bpEndPos[nHelix])*widLoop,startY-2*heiPair-(j-bpEndPos[nHelix])*heiLoop);
	      target[count_tar] = tar_mis[j]; count_tar = count_tar+1;
				} 
	   }
	   startX = startX + (N-bpEndPos[nHelix])*widLoop;
    }
	
    #plot all nucleotides	
    count_tar = count_tar-1; count_mir = count_mir-1;
	

    for (i in 1:count_mir) if (i<count_mir & i>(count_mir-8)) text(posTrack_mir[1,i],posTrack_mir[2,i],miRNA[i],cex=fontCex,col="red") else text(posTrack_mir[1,i],posTrack_mir[2,i],miRNA[i],cex=fontCex);
    for (i in 1:count_tar) text(posTrack_tar[1,i],posTrack_tar[2,i],target[i],cex=fontCex); 

    #for additional information	
    text(posTrack_mir[1,1]-widPair,posTrack_mir[2,1]+heiPair,"3'",cex=fontCex);
    text(posTrack_tar[1,1]-widPair*2,posTrack_tar[2,1],"---",cex=fontCex);text(posTrack_tar[1,1]-widPair*4,posTrack_tar[2,1],"5'",cex=fontCex);
	
    text(posTrack_mir[1,count_mir]+widPair,posTrack_mir[2,count_mir]+heiPair,"5'",cex=fontCex); 
    text(posTrack_tar[1,count_tar]+widPair*2,posTrack_tar[2,count_tar],"---",cex=fontCex);text(posTrack_tar[1,count_tar]+widPair*4,posTrack_tar[2,count_tar],"3'",cex=fontCex);
	
    lines(rep(posTrack_tar[1,targetBPstart],2),posTrack_tar[2,targetBPstart]-heiPair*c(0.5,2.3),lwd=0.5);text(posTrack_tar[1,targetBPstart],posTrack_tar[2,targetBPstart]-heiPair*3,sitePos[1],cex=fontCex);
    lines(rep(posTrack_tar[1,targetBPend],2),posTrack_tar[2,targetBPend]-heiPair*c(0.5,2.3),lwd=0.5);text(posTrack_tar[1,targetBPend],posTrack_tar[2,targetBPend]-heiPair*3,sitePos[2],cex=fontCex);
		
	
	

    #for RNA name and DeltaG_hybrid	
    text((titleStartX+titleEndX)/2,titleTopY,site[3],cex=fontCex);
    points((titleStartX+3*titleEndX)/4,max(titleTopY,posTrack_mir[2,count_mir]+heiPair)+1.2*heiLoop,pch=2,cex=wcCex);
    text((titleStartX+3*titleEndX)/4+0.5*widPair,max(titleTopY,posTrack_mir[2,count_mir]+heiPair)+1.2*heiLoop,paste("G=",site[9],"kcal/mol"),cex=fontCex,pos=4,offset=0);
	
    text((titleStartX+titleEndX)/2,titleBotY,site[2],cex=fontCex);		
	
    dev.off();
} # end function plot_Hybrid


# MAIN PROGRAM

# First parse the command arguments.
# arguments in the following order
#     Site ID
#     Target Name
#     miRNA Name
#     site position (on target, start(hyphen)end)
#     Target MisMatch
#     Target Match
#     miRNA Match
#     miRNA MisMatch
#     Delta G Hybrid

sites <- commandArgs(trailingOnly = TRUE);
sites <-  matrix(sites,1,length(sites));

plot_Hybrid(sites);